#.travis.yml

language: node_js

node_js:
  - "8"

cache: yarn

addons:
  chrome: stable

jobs:
  include:
    - stage: validation
      script: yarn build -- --no-progress
    - script: xvfb-run -a yarn test -- --single-run --no-progress --browser=ChromeNoSandbox
    - script: xvfb-run -a yarn e2e -- --no-progress --config=protractor-ci.conf.js
    - script: yarn lint

stages:
  - validation

branches:
  except:
    - /^v\d+\.\d+\.\d+.*$/
