#.travis.yml

language: node_js
node_js:
  - "8"
cache: yarn

jobs:
  include:
    - stage: validation
      script: yarn build --prod --no-progress
    - script: yarn test --no-progress --single-run
    - script: yarn e2e --no-progress
    - script: yarn lint

stages:
  - validation
